version: '3'
name: carselling-platform
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
    restart: always
  rabbitmq:
    image: rabbitmq:3.11.23-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
volumes:
  pgdata:
  mongodata: